done with the title.vedio section and the tabs
GSG-CF04/online_learning06 pull request #8
Opened 2021-10-22 20:16 UTC by SalmaIssa96

relates #4

2021-10-23 03:54 UTC, samahjamie approved these changes
well done

2021-10-23 13:16 UTC, yaqootturman requested changes
Good job Salma, I have some requests to change, check them and feel free to ask any question!

2021-10-23 13:16 UTC, yaqootturman commented on CoursePlaylist/coursePlaylist.html
> +      <section class="header">
It would be better if you use header tag rather than main and section

2021-10-23 13:16 UTC, yaqootturman commented on CoursePlaylist/coursePlaylist.html
> +              <input class="red-label" type="checkbox" checked />
I think input should be white if it doesn't checked, pseudo could help to change color for it

2021-10-23 13:16 UTC, yaqootturman commented on CoursePlaylist/coursePlaylist.css
> +@media (min-width: 786px) and (max-width: 1023px) {
for tablet min width should be 768 not 786

2021-10-23 13:16 UTC, yaqootturman commented on CoursePlaylist/coursePlaylist.html
> +            <p class="button one">Course Content</p>
Don't use numeric way to name classes, use a descriptive one,please!

2021-10-23 13:16 UTC, yaqootturman commented on CoursePlaylist/coursePlaylist.html
> +            <p class="details first">3 /5 Units ● 14 min</p>
same :(
Don't use 'first' but descriptive name,please

2021-10-23 15:46 UTC, samahjamie submitted a review, later dismissed

2021-10-23 18:37 UTC, SalmaIssa96 commented on CoursePlaylist/coursePlaylist.css
> +@media (min-width: 786px) and (max-width: 1023px) {
I took it from readme file ... so I think we should correct it in the readme file also.

2021-10-23 18:38 UTC, SalmaIssa96 commented on CoursePlaylist/coursePlaylist.html
> +            <p class="details first">3 /5 Units ● 14 min</p>
done

2021-10-23 18:38 UTC, SalmaIssa96 commented on CoursePlaylist/coursePlaylist.html
> +            <p class="button one">Course Content</p>
done

2021-10-23 18:39 UTC, SalmaIssa96 commented on CoursePlaylist/coursePlaylist.css
> +@media (min-width: 786px) and (max-width: 1023px) {
done

2021-10-23 18:39 UTC, SalmaIssa96 commented on CoursePlaylist/coursePlaylist.html
> +              <input class="red-label" type="checkbox" checked />
done

2021-10-23 18:39 UTC, SalmaIssa96 commented on CoursePlaylist/coursePlaylist.html
> +      <section class="header">
done

2021-10-25 05:15 UTC, yaqootturman requested changes

2021-10-25 05:15 UTC, yaqootturman commented on CoursePlaylist/coursePlaylist.css
> +.firstplaylist {
there is no class named firstplaylist actually, which means no need for this

2021-10-25 05:15 UTC, yaqootturman commented on CoursePlaylist/coursePlaylist.html
> +          <div class="section-with-checkbox first-box">
first-box :(
we can't name by order, orders can be change by time

2021-10-25 05:15 UTC, yaqootturman commented on CoursePlaylist/coursePlaylist.html
> +          <div class="section-with-checkbox first-box">
same for first

2021-10-25 05:15 UTC, yaqootturman commented on CoursePlaylist/coursePlaylist.html
> +    <main>
no need to put main and header in main tag, they can be separated

2021-10-25 06:19 UTC, SalmaIssa96 commented on CoursePlaylist/coursePlaylist.css
> +.firstplaylist {
done

2021-10-25 15:27 UTC, yaqootturman approved these changes

2021-10-25 15:29 UTC, samahjamie approved these changes
well done Salma <3

2021-10-25 15:34 UTC, merged